# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joneyphair
tagline:          '小世界，大梦想。'
description:      ' 小世界，大梦想。'
url:              http://joneyphair.github.io

author:
  name:           'joneyphair'
  url:            https://joneyphair.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/joneyphair
